import Alligator from "./models/Alligator.js";
import Bear from "./models/bear.js";
import Camel from "./models/camel.js";
import Duck from "./models/duck.js";
import Eagle from "./models/Eagle.js";
import Frog from "./models/Frog.js";
import Gerbil from "./models/Gerbil.js";
import Hippopotamus from "./models/Hippopotamus.js";
import Iguana from "./models/Iguana.js";
import Jellyfish from "./models/Jellyfish.js";
import Kangaroo from "./models/Kangaroo.js";
import Lemur from "./models/Lemur.js";
import Monkey from "./models/Monkey.js";
import Newt from "./models/Newt.js";
import Otter from "./models/otter.js";
import Porcupine from "./models/Porcupine.js";
import Quail from "./models/Quail.js";
import Racoon from "./models/Racoon.js";
import Snail from "./models/Snail.js";
import Toucan from "./models/Toucan.js";
import Umbrellabird from "./models/Umbrellabird.js";
import Vulture from "./models/Vulture.js";
import Wallaby from "./models/Wallaby.js";
import XRayTetra from "./models/X-ray-tetra.js";
import Yak from "./models/Yak.js";
import Zonkey from "./models/Zonkey.js";



let ally = new Alligator("Ally", "Green", "F", 200, 60, "big");
let bob = new Bear({ Name: "Bob", color: "Black", gender: "M", Weight: 200, tailLengthInch: 20, teethSize: "big" });
let camel = new Camel({ Name: "Carl", color: "Brown", gender: "M", Weight: 600, tailLengthInch: 50, teethSize: "big" });
let duck = new Duck({ Name: "Daffy", color: "blue", gender: "F", Weight: 25, tailLengthInch: 0, teethSize: "none" });
let eagle = new Eagle({ Name: "Evan", color: "brown", gender: "M", Weight: 50, tailLengthInch: 0, teethSize: "small" });
let frog = new Frog({ Name: "Fred", color: "green", gender: "F", Weight: 2, tailLengthInch: 0, teethSize: "small" });
let gerbil = new Gerbil({ Name: "Gemma", color: "black", gender: "F", Weight: 1, tailLengthInch: 1, teethSize: "small" });
let hippopotamus = new Hippopotamus({ Name: "Harold", color: "gray", gender: "M", Weight: 1000, tailLengthInch: 10, teethSize: "medium" });
let iguana = new Iguana({ Name: "Irene", color: "green", gender: "F", Weight: 5, tailLengthInch: 12, teethSize: "small" });
let jellyfish = new Jellyfish({ Name: "Joy", color: "white", gender: "F", Weight: 1, tailLengthInch: 0, teethSize: "none" });
let kangaroo = new Kangaroo({ Name: "Roo", color: "brown", gender: "M", Weight: 100, tailLengthInch: 24, teethSize: "small" });
let lemur = new Lemur({ Name: "Lori", color: "gray", gender: "F", Weight: 10, tailLengthInch: 12, teethSize: "small" });
let monkey = new Monkey({ Name: "Monte", color: "brown", gender: "M", Weight: 35, tailLengthInch: 12, teethSize: "small" });
let newt = new Newt({ Name: "Newton", color: "green", gender: "M", Weight: 3, tailLengthInch: 9, teethSize: "small" });
let otter = new Otter({ Name: "Auto", color: "brown", gender: "F", Weight: 5, tailLengthInch: 0, teethSize: "small" });
let porcupine = new Porcupine({ Name: "Peter", color: "brown", gender: "M", Weight: 25, tailLengthInch: 0, teethSize: "small" });
let quail = new Quail({ Name: "Que", color: "brown", gender: "M", Weight: 4, tailLengthInch: 0, teethSize: "small" });
let racoon = new Racoon({ Name: "Ray", color: "gray-black", gender: "M", Weight: 10, tailLengthInch: 12, teethSize: "small" });
let snail = new Snail({ Name: "Sammy", color: "brown", gender: "M", Weight: .5, tailLengthInch: 0, teethSize: "small" });
let toucan = new Toucan({ Name: "Tammy", color: "black", gender: "F", Weight: 5, tailLengthInch: 0, teethSize: "small" });
let umbrellabird = new Umbrellabird({ Name: "Uni", color: "blue", gender: "F", Weight: 3, tailLengthInch: 0, teethSize: "small" });
let vulture = new Vulture({ Name: "Venice", color: "black", gender: "F", Weight: 10, tailLengthInch: 0, teethSize: "small" });
let wallaby = new Wallaby({ Name: "Wally", color: "gray", gender: "M", Weight: 50, tailLengthInch: 12, teethSize: "small" });
let xraytetra = new XRayTetra({ Name: "Xander", color: "clear", gender: "M", Weight: .2, tailLengthInch: 1, teethSize: "small" });
let yak = new Yak({ Name: "Yolanda", color: "brown", gender: "F", Weight: 300, tailLengthInch: 24, teethSize: "medium" });
let zonkey = new Zonkey({ Name: "Zoolander", color: "black-white", gender: "M", Weight: 200, tailLengthInch: 18, teethSize: "medium" });
